# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adereco',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazar.Produto'),
        ),
        migrations.AlterField(
            model_name='calcado',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazar.Produto'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazar.Produto'),
        ),
    ]
