# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adereco',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='calcado',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='cor',
        ),
        migrations.AddField(
            model_name='adereco',
            name='foto',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='calcado',
            name='foto',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roupa',
            name='foto',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
