# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_auto_20161205_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
