# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_auto_20161205_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adereco',
            name='foto',
            field=models.ImageField(null=True, upload_to='aderecos'),
        ),
        migrations.AlterField(
            model_name='calcado',
            name='foto',
            field=models.ImageField(null=True, upload_to='calcados'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='foto',
            field=models.ImageField(null=True, upload_to='roupas'),
        ),
    ]
