# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_auto_20161205_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adereco',
            name='descricao',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calcado',
            name='descricao',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='descricao',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
